package com.furniture;

import org.springframework.boot.SpringApplication;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);        
    }
}
